In [1]:
import numpy as np
from astropy.io import fits
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
hdulist = fits.open('data/allStarLite-dr17-synspec_rev1.fits')

In [3]:
hdu1_data = hdulist[1].data

In [4]:
df4 = pd.DataFrame(hdu1_data.tolist(), columns=hdu1_data.names)

In [5]:
df = df4

In [6]:
df.columns.values

array(['APOGEE_ID', 'TELESCOPE', 'FIELD', 'ALT_ID', 'RA', 'DEC', 'GLON',
       'GLAT', 'J', 'J_ERR', 'H', 'H_ERR', 'K', 'K_ERR', 'AK_TARG',
       'AK_TARG_METHOD', 'AK_WISE', 'SFD_EBV', 'APOGEE_TARGET1',
       'APOGEE_TARGET2', 'APOGEE2_TARGET1', 'APOGEE2_TARGET2',
       'APOGEE2_TARGET3', 'APOGEE2_TARGET4', 'TARGFLAGS', 'SURVEY',
       'PROGRAMNAME', 'NVISITS', 'SNR', 'SNREV', 'STARFLAG', 'STARFLAGS',
       'ANDFLAG', 'ANDFLAGS', 'VHELIO_AVG', 'VSCATTER', 'VERR', 'RV_TEFF',
       'RV_LOGG', 'RV_FEH', 'RV_ALPHA', 'RV_CARB', 'RV_CHI2', 'RV_CCFWHM',
       'RV_AUTOFWHM', 'RV_FLAG', 'N_COMPONENTS', 'MEANFIB', 'SIGFIB',
       'MIN_H', 'MAX_H', 'MIN_JK', 'MAX_JK', 'GAIAEDR3_SOURCE_ID',
       'GAIAEDR3_PARALLAX', 'GAIAEDR3_PARALLAX_ERROR', 'GAIAEDR3_PMRA',
       'GAIAEDR3_PMRA_ERROR', 'GAIAEDR3_PMDEC', 'GAIAEDR3_PMDEC_ERROR',
       'GAIAEDR3_PHOT_G_MEAN_MAG', 'GAIAEDR3_PHOT_BP_MEAN_MAG',
       'GAIAEDR3_PHOT_RP_MEAN_MAG', 'GAIAEDR3_DR2_RADIAL_VELOCITY',
       'GAIAEDR3_DR2_RADIAL_VELOCITY_ERROR', 'GAIAEDR3_R_MED_GEO',
       'GAIAEDR3_R_LO_GEO', 'GAIAEDR3_R_HI_GEO',
       'GAIAEDR3_R_MED_PHOTOGEO', 'GAIAEDR3_R_LO_PHOTOGEO',
       'GAIAEDR3_R_HI_PHOTOGEO', 'ASPCAP_GRID', 'ASPCAP_CHI2',
       'PARAMFLAG', 'ASPCAPFLAG', 'ASPCAPFLAGS', 'FRAC_BADPIX',
       'FRAC_LOWSNR', 'FRAC_SIGSKY', 'X_H', 'X_H_ERR', 'X_M', 'X_M_ERR',
       'ELEM_CHI2', 'ELEMFRAC', 'EXTRATARG', 'MEMBERFLAG', 'MEMBER',
       'X_H_SPEC', 'X_M_SPEC', 'TEFF', 'TEFF_ERR', 'LOGG', 'LOGG_ERR',
       'M_H', 'M_H_ERR', 'ALPHA_M', 'ALPHA_M_ERR', 'VMICRO', 'VMACRO',
       'VSINI', 'TEFF_SPEC', 'LOGG_SPEC', 'C_FE', 'C_FE_SPEC', 'C_FE_ERR',
       'C_FE_FLAG', 'CI_FE', 'CI_FE_SPEC', 'CI_FE_ERR', 'CI_FE_FLAG',
       'N_FE', 'N_FE_SPEC', 'N_FE_ERR', 'N_FE_FLAG', 'O_FE', 'O_FE_SPEC',
       'O_FE_ERR', 'O_FE_FLAG', 'NA_FE', 'NA_FE_SPEC', 'NA_FE_ERR',
       'NA_FE_FLAG', 'MG_FE', 'MG_FE_SPEC', 'MG_FE_ERR', 'MG_FE_FLAG',
       'AL_FE', 'AL_FE_SPEC', 'AL_FE_ERR', 'AL_FE_FLAG', 'SI_FE',
       'SI_FE_SPEC', 'SI_FE_ERR', 'SI_FE_FLAG', 'P_FE', 'P_FE_SPEC',
       'P_FE_ERR', 'P_FE_FLAG', 'S_FE', 'S_FE_SPEC', 'S_FE_ERR',
       'S_FE_FLAG', 'K_FE', 'K_FE_SPEC', 'K_FE_ERR', 'K_FE_FLAG', 'CA_FE',
       'CA_FE_SPEC', 'CA_FE_ERR', 'CA_FE_FLAG', 'TI_FE', 'TI_FE_SPEC',
       'TI_FE_ERR', 'TI_FE_FLAG', 'TIII_FE', 'TIII_FE_SPEC',
       'TIII_FE_ERR', 'TIII_FE_FLAG', 'V_FE', 'V_FE_SPEC', 'V_FE_ERR',
       'V_FE_FLAG', 'CR_FE', 'CR_FE_SPEC', 'CR_FE_ERR', 'CR_FE_FLAG',
       'MN_FE', 'MN_FE_SPEC', 'MN_FE_ERR', 'MN_FE_FLAG', 'FE_H',
       'FE_H_SPEC', 'FE_H_ERR', 'FE_H_FLAG', 'CO_FE', 'CO_FE_SPEC',
       'CO_FE_ERR', 'CO_FE_FLAG', 'NI_FE', 'NI_FE_SPEC', 'NI_FE_ERR',
       'NI_FE_FLAG', 'CU_FE', 'CU_FE_SPEC', 'CU_FE_ERR', 'CU_FE_FLAG',
       'CE_FE', 'CE_FE_SPEC', 'CE_FE_ERR', 'CE_FE_FLAG'], dtype=object)

In [7]:
# subset all chemical abundances (collumn name contain "_FE")
chemical_subset = df.filter(regex='_FE', axis=1) 

# merge with + df.filter(regex='_H', axis=1)
chemical_subset = pd.concat([chemical_subset, df.filter(regex='_H', axis=1)], axis=1)

In [8]:
physical_properties_subset = df[['TEFF', 'LOGG', 'M_H', 'J_ERR', 'H_ERR', 'K_ERR', 'VSINI', 'VMICRO', 'VMACRO']]

In [9]:
chemical_subset = chemical_subset.filter(regex='_ERR', axis=1)

In [23]:
chemical_subset.describe()

,C_FE_ERR,CI_FE_ERR,N_FE_ERR,O_FE_ERR,NA_FE_ERR,MG_FE_ERR,AL_FE_ERR,SI_FE_ERR,P_FE_ERR,S_FE_ERR,...,TIII_FE_ERR,V_FE_ERR,CR_FE_ERR,MN_FE_ERR,CO_FE_ERR,NI_FE_ERR,CU_FE_ERR,CE_FE_ERR,M_H_ERR,FE_H_ERR
count,643860.000000,640781.000000,591028.000000,643504.000000,567221.000000,646291.000000,572099.000000,646151.000000,636261.000000,558938.000000,...,363726.000000,549071.000000,569551.000000,578038.000000,388270.000000,633827.000000,442416.000000,353995.000000,647025.000000,647042.000000
mean,0.032428,0.039857,0.401140,0.042395,0.121341,0.017945,0.026643,0.020172,0.143686,0.061941,...,0.105233,0.125944,0.067376,0.021551,0.091706,0.018935,0.103878,0.103885,0.010982,0.010603
std,0.234594,0.163272,7.954775,0.063144,0.107488,0.022260,0.010719,0.023800,0.073300,0.037435,...,0.076270,0.088678,0.053385,0.012419,0.082371,0.010740,0.608181,0.131483,0.028008,0.007448
min,0.005958,0.011322,0.006810,0.005896,0.017592,0.007364,0.010280,0.008938,0.017094,0.019235,...,0.035146,0.019372,0.012130,0.005199,0.012699,0.005889,0.000587,0.027156,0.003098,0.003032
25%,0.013509,0.025173,0.016402,0.014940,0.063136,0.012258,0.018954,0.013756,0.101531,0.040645,...,0.072062,0.071685,0.038638,0.014448,0.045742,0.012312,0.013521,0.061052,0.006633,0.007584
50%,0.019634,0.033456,0.023608,0.023410,0.093562,0.015067,0.023943,0.017258,0.133767,0.053364,...,0.091668,0.104428,0.054666,0.018534,0.068742,0.016329,0.054230,0.083012,0.008306,0.009504
75%,0.032344,0.043997,0.036741,0.044206,0.145074,0.019048,0.032589,0.022193,0.173415,0.072602,...,0.120940,0.155205,0.079009,0.025084,0.110613,0.022474,0.092658,0.118397,0.010687,0.012109
max,67.712769,90.253571,1586.033081,9.280841,2.402143,4.857286,0.700300,8.129145,1.431538,3.381464,...,3.910026,1.838147,1.906017,1.778314,2.117604,1.736116,60.004436,3.046578,4.833942,1.469320

In [39]:
physical_properties_subset.describe()

,TEFF,LOGG,M_H,J_ERR,H_ERR,K_ERR,VSINI,VMICRO,VMACRO
count,689024.000000,689024.000000,647025.000000,722680.000000,722006.000000,721512.000000,316812.000000,689024.000000,689024.000000
mean,4994.286917,3.082897,-0.232709,0.024710,0.026333,0.023649,10.734419,1.152248,1.986807
std,1338.033566,1.234761,0.381630,0.029999,0.042978,0.076668,20.747286,0.665692,2.040843
min,3088.049805,-0.482825,-2.468600,0.000000,0.000000,0.000000,1.499996,0.299999,0.000000
25%,4377.779541,2.278944,-0.401310,0.022000,0.022000,0.019000,1.549173,0.545858,0.000000
50%,4792.267822,2.984478,-0.173630,0.023000,0.024000,0.021000,3.137979,1.187385,2.593465
75%,5214.606567,4.314916,0.013517,0.026000,0.028000,0.024000,7.348903,1.510463,3.498560
max,19869.988281,5.391378,0.968570,9.998000,9.999000,9.998000,96.006363,4.799986,12.765858

In [43]:
physical_properties_subset['VMACRO']

0         0.000000
1         3.223484
2         0.000000
3         0.000000
4         0.000000
            ...
733896         NaN
733897    3.381057
733898    2.756312
733899    5.439030
733900    0.000000
Name: VMACRO, Length: 733901, dtype: float64

In [27]:
def calculate_decile_intervals(df, decimals=3):
    intervals = {}
    for column in df.select_dtypes(include=[np.number]).columns:
        # Exclure les NaN pour le calcul
        valid_data = df[column].dropna()
        if not valid_data.empty:
            deciles = np.percentile(valid_data, q=np.arange(0, 101, 10))
            # Ajuster les bornes
            deciles[0] = np.floor(deciles[0] * 10**decimals) / 10**decimals  # Arrondi au-dessous pour le premier
            deciles[-1] = np.ceil(deciles[-1] * 10**decimals) / 10**decimals  # Arrondi au-dessus pour le dernier
            
            # Créer les intervalles avec arrondi
            intervals[column] = [
                (round(deciles[i], decimals), round(deciles[i + 1], decimals)) 
                for i in range(len(deciles) - 1)
            ]
        else:
            intervals[column] = [(np.nan, np.nan) for _ in range(10)]
    return pd.DataFrame.from_dict(intervals, orient='index').transpose()

In [28]:
def calculate_decile_intervals_all_columns(df, decimals=3):
    intervals = {}
    for column in df.select_dtypes(include=[np.number]).columns:
        # Exclure les NaN pour le calcul
        valid_data = df[column].dropna()
        if not valid_data.empty:
            deciles = np.percentile(valid_data, q=np.arange(0, 101, 10))
            # Ajuster les bornes
            deciles[0] = np.floor(deciles[0] * 10**decimals) / 10**decimals  # Arrondi au-dessous pour le premier
            deciles[-1] = np.ceil(deciles[-1] * 10**decimals) / 10**decimals  # Arrondi au-dessus pour le dernier
            
            # Créer les intervalles avec arrondi
            intervals[f"{column}_RANGE"] = [
                (round(deciles[i], decimals), round(deciles[i + 1], decimals)) 
                for i in range(len(deciles) - 1)
            ]
        else:
            intervals[f"{column}_RANGE"] = [(np.nan, np.nan) for _ in range(10)]
    return pd.DataFrame.from_dict(intervals, orient='index').transpose()

In [33]:
# Dataset des intervalles
df_intervals_chemicals = calculate_decile_intervals_all_columns(chemical_subset)

In [35]:
df_intervals_chemicals

,C_FE_ERR_RANGE,CI_FE_ERR_RANGE,N_FE_ERR_RANGE,O_FE_ERR_RANGE,NA_FE_ERR_RANGE,MG_FE_ERR_RANGE,AL_FE_ERR_RANGE,SI_FE_ERR_RANGE,P_FE_ERR_RANGE,S_FE_ERR_RANGE,...,TIII_FE_ERR_RANGE,V_FE_ERR_RANGE,CR_FE_ERR_RANGE,MN_FE_ERR_RANGE,CO_FE_ERR_RANGE,NI_FE_ERR_RANGE,CU_FE_ERR_RANGE,CE_FE_ERR_RANGE,M_H_ERR_RANGE,FE_H_ERR_RANGE
0,"(0.005, 0.011)","(0.011, 0.021)","(0.006, 0.013)","(0.005, 0.011)","(0.017, 0.047)","(0.007, 0.011)","(0.01, 0.016)","(0.008, 0.012)","(0.017, 0.068)","(0.019, 0.033)",...,"(0.035, 0.06)","(0.019, 0.052)","(0.012, 0.03)","(0.005, 0.012)","(0.012, 0.033)","(0.005, 0.01)","(0.0, 0.006)","(0.027, 0.046)","(0.003, 0.006)","(0.003, 0.007)"
1,"(0.011, 0.013)","(0.021, 0.024)","(0.013, 0.015)","(0.011, 0.014)","(0.047, 0.058)","(0.011, 0.012)","(0.016, 0.018)","(0.012, 0.013)","(0.068, 0.093)","(0.033, 0.038)",...,"(0.06, 0.068)","(0.052, 0.065)","(0.03, 0.036)","(0.012, 0.014)","(0.033, 0.042)","(0.01, 0.012)","(0.006, 0.01)","(0.046, 0.057)","(0.006, 0.006)","(0.007, 0.007)"
2,"(0.013, 0.015)","(0.024, 0.027)","(0.015, 0.018)","(0.014, 0.016)","(0.058, 0.068)","(0.012, 0.013)","(0.018, 0.02)","(0.013, 0.014)","(0.093, 0.109)","(0.038, 0.043)",...,"(0.068, 0.076)","(0.065, 0.078)","(0.036, 0.042)","(0.014, 0.015)","(0.042, 0.05)","(0.012, 0.013)","(0.01, 0.018)","(0.057, 0.065)","(0.006, 0.007)","(0.007, 0.008)"
3,"(0.015, 0.017)","(0.027, 0.03)","(0.018, 0.02)","(0.016, 0.02)","(0.068, 0.08)","(0.013, 0.014)","(0.02, 0.021)","(0.014, 0.016)","(0.109, 0.121)","(0.043, 0.048)",...,"(0.076, 0.083)","(0.078, 0.09)","(0.042, 0.048)","(0.015, 0.017)","(0.05, 0.059)","(0.013, 0.014)","(0.018, 0.038)","(0.065, 0.074)","(0.007, 0.008)","(0.008, 0.009)"
4,"(0.017, 0.02)","(0.03, 0.033)","(0.02, 0.024)","(0.02, 0.023)","(0.08, 0.094)","(0.014, 0.015)","(0.021, 0.024)","(0.016, 0.017)","(0.121, 0.134)","(0.048, 0.053)",...,"(0.083, 0.092)","(0.09, 0.104)","(0.048, 0.055)","(0.017, 0.019)","(0.059, 0.069)","(0.014, 0.016)","(0.038, 0.054)","(0.074, 0.083)","(0.008, 0.008)","(0.009, 0.01)"
5,"(0.02, 0.023)","(0.033, 0.037)","(0.024, 0.028)","(0.023, 0.029)","(0.094, 0.11)","(0.015, 0.016)","(0.024, 0.027)","(0.017, 0.019)","(0.134, 0.147)","(0.053, 0.06)",...,"(0.092, 0.101)","(0.104, 0.121)","(0.055, 0.063)","(0.019, 0.021)","(0.069, 0.082)","(0.016, 0.018)","(0.054, 0.067)","(0.083, 0.095)","(0.008, 0.009)","(0.01, 0.01)"
6,"(0.023, 0.029)","(0.037, 0.041)","(0.028, 0.033)","(0.029, 0.038)","(0.11, 0.131)","(0.016, 0.018)","(0.027, 0.031)","(0.019, 0.021)","(0.147, 0.164)","(0.06, 0.068)",...,"(0.101, 0.114)","(0.121, 0.142)","(0.063, 0.073)","(0.021, 0.023)","(0.082, 0.1)","(0.018, 0.021)","(0.067, 0.083)","(0.095, 0.11)","(0.009, 0.01)","(0.01, 0.011)"
7,"(0.029, 0.038)","(0.041, 0.047)","(0.033, 0.043)","(0.038, 0.054)","(0.131, 0.162)","(0.018, 0.02)","(0.031, 0.035)","(0.021, 0.024)","(0.164, 0.185)","(0.068, 0.078)",...,"(0.114, 0.129)","(0.142, 0.17)","(0.073, 0.086)","(0.023, 0.027)","(0.1, 0.124)","(0.021, 0.024)","(0.083, 0.106)","(0.11, 0.129)","(0.01, 0.011)","(0.011, 0.013)"
8,"(0.038, 0.055)","(0.047, 0.056)","(0.043, 0.081)","(0.054, 0.096)","(0.162, 0.218)","(0.02, 0.024)","(0.035, 0.04)","(0.024, 0.028)","(0.185, 0.219)","(0.078, 0.096)",...,"(0.129, 0.154)","(0.17, 0.218)","(0.086, 0.111)","(0.027, 0.033)","(0.124, 0.168)","(0.024, 0.03)","(0.106, 0.154)","(0.129, 0.157)","(0.011, 0.014)","(0.013, 0.015)"
9,"(0.055, 67.713)","(0.056, 90.254)","(0.081, 1586.034)","(0.096, 9.281)","(0.218, 2.403)","(0.024, 4.858)","(0.04, 0.701)","(0.028, 8.13)","(0.219, 1.432)","(0.096, 3.382)",...,"(0.154, 3.911)","(0.218, 1.839)","(0.111, 1.907)","(0.033, 1.779)","(0.168, 2.118)","(0.03, 1.737)","(0.154, 60.005)","(0.157, 3.047)","(0.014, 4.834)","(0.015, 1.47)"

In [40]:
df_intervals_physical_properties = calculate_decile_intervals_all_columns(physical_properties_subset)

In [44]:
df_intervals_physical_properties

,TEFF_RANGE,LOGG_RANGE,M_H_RANGE,J_ERR_RANGE,H_ERR_RANGE,K_ERR_RANGE,VSINI_RANGE,VMICRO_RANGE,VMACRO_RANGE
0,"(3088.049, 3927.348)","(-0.483, 1.35)","(-2.469, -0.636)","(0.0, 0.02)","(0.0, 0.019)","(0.0, 0.017)","(1.499, 1.505)","(0.299, 0.328)","(0.0, 0.0)"
1,"(3927.348, 4237.016)","(1.35, 1.987)","(-0.636, -0.459)","(0.02, 0.021)","(0.019, 0.021)","(0.017, 0.019)","(1.505, 1.518)","(0.328, 0.386)","(0.0, 0.0)"
2,"(4237.016, 4511.848)","(1.987, 2.404)","(-0.459, -0.349)","(0.021, 0.022)","(0.021, 0.022)","(0.019, 0.02)","(1.518, 1.753)","(0.386, 0.786)","(0.0, 0.0)"
3,"(4511.848, 4668.466)","(2.404, 2.555)","(-0.349, -0.255)","(0.022, 0.023)","(0.022, 0.023)","(0.02, 0.021)","(1.753, 2.469)","(0.786, 1.0)","(0.0, 0.0)"
4,"(4668.466, 4792.268)","(2.555, 2.984)","(-0.255, -0.174)","(0.023, 0.023)","(0.023, 0.024)","(0.021, 0.021)","(2.469, 3.138)","(1.0, 1.187)","(0.0, 2.593)"
5,"(4792.268, 4907.944)","(2.984, 3.75)","(-0.174, -0.099)","(0.023, 0.024)","(0.024, 0.026)","(0.021, 0.023)","(3.138, 4.409)","(1.187, 1.321)","(2.593, 2.998)"
6,"(4907.944, 5051.44)","(3.75, 4.18)","(-0.099, -0.026)","(0.024, 0.025)","(0.026, 0.027)","(0.023, 0.023)","(4.409, 6.237)","(1.321, 1.443)","(2.998, 3.329)"
7,"(5051.44, 5530.488)","(4.18, 4.464)","(-0.026, 0.056)","(0.025, 0.026)","(0.027, 0.03)","(0.023, 0.025)","(6.237, 9.869)","(1.443, 1.587)","(3.329, 3.682)"
8,"(5530.488, 5983.174)","(4.464, 4.581)","(0.056, 0.162)","(0.026, 0.029)","(0.03, 0.033)","(0.025, 0.029)","(9.869, 26.254)","(1.587, 1.83)","(3.682, 4.133)"
9,"(5983.174, 19869.989)","(4.581, 5.392)","(0.162, 0.969)","(0.029, 9.999)","(0.033, 9.999)","(0.029, 9.999)","(26.254, 96.007)","(1.83, 4.8)","(4.133, 12.766)"

In [106]:
range_df = pd.DataFrame()
print(range_df)

Empty DataFrame
Columns: []
Index: []

In [118]:
colonnes_chemicals = list(chemical_subset.columns.values)
colonnes_physical = ['TEFF', 'LOGG', 'M_H', 'J_ERR', 'H_ERR', 'K_ERR', 'VSINI', 'VMICRO', 'VMACRO']

colonnes_physical_reduced = ['TEFF', 'LOGG', 'VSINI', 'VMICRO', 'VMACRO', 'J_ERR', 'H_ERR', 'K_ERR']
colonnes_physical_removed = ['M_H']

colonnes_chemicals_reduced = colonnes_chemicals
colonnes_chemicals_reduced.remove('X_H_ERR')
colonnes_chemicals_removed = ['X_H_ERR']

In [119]:
for col in colonnes_chemicals_reduced:
    range_df[f'{col}_LOG'] = np.log1p(df[col])
    range_df[f'{col}_LOG_RANGE'] = pd.qcut(range_df[f'{col}_LOG'], q=10, duplicates='drop')

In [130]:
for col in colonnes_chemicals_removed:
    range_df[f'{col}_LOG'] = np.log1p(df[col])
    range_df[f'{col}_LOG_RANGE'] = pd.qcut(range_df[f'{col}_LOG'], q=10, duplicates='drop')

TypeError: loop of ufunc does not support argument 0 of type list which has no callable log1p method

In [129]:
for col in colonnes_physical_removed:
    print(f"Processing column: {col}")
    print(df[col].describe())  # Statistiques descriptives
    print(df[col].isna().sum(), "NaN values")

Processing column: M_H
count    647025.000000
mean         -0.232709
std           0.381630
min          -2.468600
25%          -0.401310
50%          -0.173630
75%           0.013517
max           0.968570
Name: M_H, dtype: float64
86876 NaN values

In [122]:
for col in colonnes_physical_reduced:
    print(col)
    range_df[f'{col}_LOG'] = np.log1p(df[col])
    range_df[f'{col}_LOG_RANGE'] = pd.qcut(range_df[f'{col}_LOG'], q=10, duplicates='drop')

TEFF
LOGG
VSINI
VMICRO
VMACRO
J_ERR
H_ERR
K_ERR

In [131]:
for col in colonnes_physical_removed:
    print(col)
    range_df[f'{col}_LOG'] = np.log1p(df[col])
    range_df[f'{col}_LOG_RANGE'] = pd.qcut(range_df[f'{col}_LOG'], q=10, duplicates='drop')

M_H

c:\ProgramData\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\ProgramData\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: invalid value encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\ProgramData\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4657: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))

ValueError: missing values must be missing in the same location both left and right sides